In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentences
sent=[ 'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]



In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [5]:
## One hot representation for every word

one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[3041, 9442, 3436, 1272],
 [3041, 9442, 3436, 7457],
 [3041, 9207, 3436, 6013],
 [4027, 3688, 8071, 6612, 959],
 [4027, 3688, 8071, 6612, 2011],
 [2615, 3041, 1864, 3436, 4519],
 [1562, 7635, 2500, 6612]]

In [8]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [11]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3041 9442 3436 1272]
 [   0    0    0    0 3041 9442 3436 7457]
 [   0    0    0    0 3041 9207 3436 6013]
 [   0    0    0 4027 3688 8071 6612  959]
 [   0    0    0 4027 3688 8071 6612 2011]
 [   0    0    0 2615 3041 1864 3436 4519]
 [   0    0    0    0 1562 7635 2500 6612]]


In [12]:
## Feature Representation 
dim = 10 


In [13]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 170ms/step


array([[[ 0.04815492, -0.00336934, -0.02162144,  0.03776708,
          0.01758612,  0.04600506,  0.01060284,  0.04539737,
          0.01744277,  0.02048166],
        [ 0.04815492, -0.00336934, -0.02162144,  0.03776708,
          0.01758612,  0.04600506,  0.01060284,  0.04539737,
          0.01744277,  0.02048166],
        [ 0.04815492, -0.00336934, -0.02162144,  0.03776708,
          0.01758612,  0.04600506,  0.01060284,  0.04539737,
          0.01744277,  0.02048166],
        [ 0.04815492, -0.00336934, -0.02162144,  0.03776708,
          0.01758612,  0.04600506,  0.01060284,  0.04539737,
          0.01744277,  0.02048166],
        [-0.04003574, -0.00394223, -0.00879958,  0.04440707,
          0.00474715, -0.02838929,  0.04876507, -0.04683935,
         -0.01310829, -0.00932945],
        [ 0.03270287, -0.04975436, -0.02943246, -0.03260063,
          0.01501361,  0.03134009,  0.0300122 , -0.01808899,
          0.00313215, -0.03629738],
        [-0.00120481,  0.03655681, -0.012133  ,  0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 3041, 9442, 3436, 1272])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 42ms/step


array([[ 0.04815492, -0.00336934, -0.02162144,  0.03776708,  0.01758612,
         0.04600506,  0.01060284,  0.04539737,  0.01744277,  0.02048166],
       [ 0.04815492, -0.00336934, -0.02162144,  0.03776708,  0.01758612,
         0.04600506,  0.01060284,  0.04539737,  0.01744277,  0.02048166],
       [ 0.04815492, -0.00336934, -0.02162144,  0.03776708,  0.01758612,
         0.04600506,  0.01060284,  0.04539737,  0.01744277,  0.02048166],
       [ 0.04815492, -0.00336934, -0.02162144,  0.03776708,  0.01758612,
         0.04600506,  0.01060284,  0.04539737,  0.01744277,  0.02048166],
       [-0.04003574, -0.00394223, -0.00879958,  0.04440707,  0.00474715,
        -0.02838929,  0.04876507, -0.04683935, -0.01310829, -0.00932945],
       [ 0.03270287, -0.04975436, -0.02943246, -0.03260063,  0.01501361,
         0.03134009,  0.0300122 , -0.01808899,  0.00313215, -0.03629738],
       [-0.00120481,  0.03655681, -0.012133  ,  0.01628831, -0.0220856 ,
        -0.03334476,  0.01461445,  0.01728884